language: node_js

node_js:
  - "10"

# Se consideran todas las ramas 
branches:
  only:
  - gh-pages
  - /.*/

cache: yarn

directories:
  - node_modules

services:
  - postgresql

before_script:
  - yarn --frozen-lockfile
  - psql -c 'create database questudio;' -U postgres

# Aca se debe configurar el comando pa testing
script:
- yarn test

# Configuracion para heroku
deploy:
  provider: heroku
  app: questudio
  on: master
  run: 
    - "sequelize db:migrate"
    - "sequelize db:seed:all"
