language: node_js

node_js:
  - "10"

# Se consideran todas las ramas 
branches:
  only:
  - /.*/

cache: yarn

directories:
  - node_modules

services:
  - postgresql

before_script:
  - yarn --frozen-lockfile
  - psql -c 'create database questudio;' -U postgres

install:
  - yarn install

script:
  - yarn test

# Configuracion para heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: questudio-cl
  on: 
    - master
    - development
  run: 
    - "sequelize db:migrate"
    - "sequelize db:seed:all"
