language: node_js

node_js:
  - "stable"

branches:
  - master
  - development
  - travis

cache: yarn

directories:
  - node_modules

services:
  - postgresql

before_script:
  - yarn --frozen-lockfile
  - psql -c 'create database questudio;' -U postgres

script:
- yarn start

deploy:
  provider: heroku
  api_key: f2386d6d-3350-460a-ac27-25b5421ba7f2
  on: master
  run: 
    - "sequelize db:migrate"
    - "sequelize db:seed:all"
